name: Deploy Inertia App to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to cPanel
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2

      # Step 2: Set up PHP and Composer (Backend)
      - name: Set up PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # Match your app's PHP version
          tools: composer

      # Step 3: Disable Pusher autodiscovery in composer.json
      - name: Disable Pusher Autodiscovery
        run: |
          if grep -q '"dont-discover"' composer.json; then
            sed -i 's/"dont-discover": \[/"dont-discover": ["pusher\/pusher-php-server", /' composer.json
          else
            sed -i 's/"extra": {/"extra": {"laravel": {"dont-discover": ["pusher\/pusher-php-server"]}, /' composer.json
          fi

      # Step 4: Install PHP dependencies
      - name: Install Composer Dependencies
        run: |
          composer install --no-dev --optimize-autoloader
          composer require tightenco/ziggy

      # Step 5: Cache and clear configuration (Important for env variables to apply)
      - name: Cache and Clear Config
        run: |
          php artisan config:clear
          php artisan cache:clear
          php artisan config:cache

      # Step 6: Set up Node.js and build assets (Frontend)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21' # Match the required Node.js version
          
      - name: Install Node.js dependencies
        run: npm install

      - name: Build Assets
        run: npm run build

      # Step 7: Deploy to cPanel using FTP
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}