name: Deploy Inertia App to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to cPanel
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2

      # Step 2: Set up PHP and Composer (Backend)
      - name: Set up PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # Match your app's PHP version
          tools: composer

      # Step 3: Install PHP dependencies (including tightenco/ziggy)
      - name: Install Composer Dependencies
        run: |
          composer install --no-dev --optimize-autoloader
          composer require tightenco/ziggy

      # Step 4: Set up Pusher environment variables
      - name: Configure Environment Variables
        run: |
          echo "PUSHER_APP_ID=${{ secrets.PUSHER_APP_ID }}" >> .env
          echo "PUSHER_APP_KEY=${{ secrets.PUSHER_APP_KEY }}" >> .env
          echo "PUSHER_APP_SECRET=${{ secrets.PUSHER_APP_SECRET }}" >> .env
          echo "PUSHER_APP_CLUSTER=${{ secrets.PUSHER_APP_CLUSTER }}" >> .env

      # Step 5: Cache and clear configuration (Important for env variables to apply)
      - name: Cache and Clear Config
        run: |
          php artisan config:clear
          php artisan cache:clear
          php artisan config:cache

      # Step 6: Set up Node.js and build assets (Frontend)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21' # Match the required Node.js version
          
      - name: Install Node.js dependencies
        run: npm install

      - name: Build Assets
        run: npm run build

      # Step 7: Deploy to cPanel using FTP
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
