name: Deploy Inertia App to cPanel

on:
  push:
    branches:
      - FixingGithubActions

jobs:
  deploy:
    name: Deploy to cPanel
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2

      # Step 2: Set up PHP and Composer first (backend dependencies)
      - name: Set up PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # Match your app's PHP version
          tools: composer

      # Step 3: Install PHP dependencies (including tightenco/ziggy)
      - name: Install Composer Dependencies
        run: |
          composer install --no-dev --optimize-autoloader
          composer require tightenco/ziggy # Ensure Ziggy is installed

      # Step 4: Set up Node.js and build assets (frontend)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21' # Match the required Node.js version
          
      - name: Install Node.js dependencies
        run: npm install

      - name: Build Assets
        run: npm run build

      # Step 5: Create .env file with hardcoded Pusher credentials
      - name: Set up environment file
        run: |
          echo "APP_ENV=production" >> .env
          echo "PUSHER_APP_ID=1939729" >> .env
          echo "PUSHER_APP_KEY=dc7341bc673250f3fc36" >> .env
          echo "PUSHER_APP_SECRET=25f43953d99c2d5da7ed" >> .env
          echo "PUSHER_APP_CLUSTER=mt1" >> .env
          echo "PUSHER_USE_TLS=true" >> .env

      # Step 6: Clear and cache Laravel config
      - name: Clear and cache Laravel config
        run: |
          php artisan config:clear
          php artisan cache:clear
          php artisan config:cache

      # Step 7: Deploy to cPanel using FTP
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: "your-server.com"
          username: "your-ftp-username"
          password: "your-ftp-password"
